version: '3.4'

networks:
  default:

volumes:
  backend-postgres-data:
    external: true

services:
  nginx:
    build:
      context: ./local
      dockerfile: Dockerfile_nginx
    container_name: backend_nginx
    restart: always
    networks:
      - default
    ports:
      - 2860:80
    volumes:
      - &data-app ../:/app
      - ./local/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./local/config/nginx/site.conf:/etc/nginx/site.conf
    depends_on:
      - fpm

  fpm: &fpm-container
    build:
      context: ./local
      target: app
      dockerfile: Dockerfile_fpm
    volumes:
      - *data-app
      - ./local/config/fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./local/config/fpm/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    container_name: backend_fpm
    depends_on:
      - database

  database:
    image: postgres:14.2
    container_name: backend_postgres
    working_dir: /app
    restart: always
    environment:
      POSTGRES_PASSWORD: 7f7AvS82PvJebYqk
      POSTGRES_USER: backend
    volumes:
      - backend-postgres-data:/var/lib/postgesql/data
    ports:
      - 5440:5432

  rabbitmq:
    container_name: backend_rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 15672:15672